version: 0.1

input:
  # dataset
  scale_height: 64
  max_size:  # [H, W] or None
  train_path: './data/train.txt'
  val_path: './data/val.txt'
  test_path: './data/test.txt'
  vocab_path: './vocab.txt'

  # normalize
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  shear: 5
  fillcolor: [255]

model:
  backbone:
    arch: 'resnet34'
    droplast: 2
    freeze: False

  embed_size: 512
